# Generated by Django 6.0.4 on 2026-04-08 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('Mid', 'Mid Term'), ('Half Yearly', 'Half Yearly'), ('Pre Test', 'Pre Test'), ('Test', 'Test')], max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='fourth_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fourth_subject_students', to='students.subject'),
        ),
    ]
