# Generated by Django 6.0.4 on 2026-04-09 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_exam_exam_type_alter_student_fourth_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='obtained_marks',
        ),
        migrations.AddField(
            model_name='mark',
            name='cq_marks',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='mark',
            name='is_absent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mark',
            name='lab_marks',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='mark',
            name='mcq_marks',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('Mid-Term', 'Mid-Term'), ('Half Yearly', 'Half Yearly'), ('Pre-Test', 'Pre-Test'), ('Test', 'Test')], max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.CharField(choices=[('Science', 'Science'), ('Commerce', 'Commerce'), ('Humanities', 'Humanities')], max_length=20),
        ),
    ]
