# Generated by Django 6.0.4 on 2026-04-09 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_academicsession_exam_session_obj_student_session_obj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='session',
        ),
        migrations.RemoveField(
            model_name='student',
            name='session',
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='session_obj',
            new_name='session',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='session_obj',
            new_name='session',
        ),
    ]
