# Generated by Django 6.0.4 on 2026-04-10 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pds_id', models.CharField(max_length=50, unique=True, verbose_name='PDS ID')),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255, verbose_name='Post')),
                ('subject', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='teachers_profile/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
